services:
  postgres:
    image: postgres:15
    container_name: postgres_crud
    restart: always
    environment:
      POSTGRES_DB: lab_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: ./app
    container_name: app_crud
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  nginx:
    image: nginx:alpine
    container_name: nginx_crud
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  postgres_data:
